config/routes.rb
Rails.application.routes.draw do
  resources :prospects
  resources :salesmen
  resources :dealerships
  resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/dealership.rb
class Dealership < ActiveRecord::Base
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
end

app/models/salesman.rb
class Salesman < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :year, :condition, :location_address, :location_city, :location_state, :location_zip, :price, :status, :sold_by)
    end
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :set_dealership, only: [:show, :edit, :update, :destroy]

  # GET /dealerships
  # GET /dealerships.json
  def index
    @dealerships = Dealership.all
  end

  # GET /dealerships/1
  # GET /dealerships/1.json
  def show
  end

  # GET /dealerships/new
  def new
    @dealership = Dealership.new
  end

  # GET /dealerships/1/edit
  def edit
  end

  # POST /dealerships
  # POST /dealerships.json
  def create
    @dealership = Dealership.new(dealership_params)

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to @dealership, notice: 'Dealership was successfully created.' }
        format.json { render :show, status: :created, location: @dealership }
      else
        format.html { render :new }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealerships/1
  # PATCH/PUT /dealerships/1.json
  def update
    respond_to do |format|
      if @dealership.update(dealership_params)
        format.html { redirect_to @dealership, notice: 'Dealership was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealership }
      else
        format.html { render :edit }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1
  # DELETE /dealerships/1.json
  def destroy
    @dealership.destroy
    respond_to do |format|
      format.html { redirect_to dealerships_url, notice: 'Dealership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = Dealership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealership_params
      params.require(:dealership).permit(:name, :address, :city, :state, :zip, :owner)
    end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]

  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.all
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'Prospect was successfully created.' }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1
  # PATCH/PUT /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: 'Prospect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_params
      params.require(:prospect).permit(:first_name, :last_name, :email_address, :address, :city, :state, :zip, :mobile_phone_number)
    end
end

app/controllers/salesmen_controller.rb
class SalesmenController < ApplicationController
  before_action :set_salesman, only: [:show, :edit, :update, :destroy]

  # GET /salesmen
  # GET /salesmen.json
  def index
    @salesmen = Salesman.all
  end

  # GET /salesmen/1
  # GET /salesmen/1.json
  def show
  end

  # GET /salesmen/new
  def new
    @salesman = Salesman.new
  end

  # GET /salesmen/1/edit
  def edit
  end

  # POST /salesmen
  # POST /salesmen.json
  def create
    @salesman = Salesman.new(salesman_params)

    respond_to do |format|
      if @salesman.save
        format.html { redirect_to @salesman, notice: 'Salesman was successfully created.' }
        format.json { render :show, status: :created, location: @salesman }
      else
        format.html { render :new }
        format.json { render json: @salesman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salesmen/1
  # PATCH/PUT /salesmen/1.json
  def update
    respond_to do |format|
      if @salesman.update(salesman_params)
        format.html { redirect_to @salesman, notice: 'Salesman was successfully updated.' }
        format.json { render :show, status: :ok, location: @salesman }
      else
        format.html { render :edit }
        format.json { render json: @salesman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salesmen/1
  # DELETE /salesmen/1.json
  def destroy
    @salesman.destroy
    respond_to do |format|
      format.html { redirect_to salesmen_url, notice: 'Salesman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salesman
      @salesman = Salesman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salesman_params
      params.require(:salesman).permit(:first_name, :last_name, :email_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/salesmen_helper.rb
module SalesmenHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :location_address %><br>
    <%= f.text_field :location_address %>
  </div>
  <div class="field">
    <%= f.label :location_city %><br>
    <%= f.text_field :location_city %>
  </div>
  <div class="field">
    <%= f.label :location_state %><br>
    <%= f.text_field :location_state %>
  </div>
  <div class="field">
    <%= f.label :location_zip %><br>
    <%= f.text_field :location_zip %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :sold_by %><br>
    <%= f.text_field :sold_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Year</th>
      <th>Condition</th>
      <th>Location address</th>
      <th>Location city</th>
      <th>Location state</th>
      <th>Location zip</th>
      <th>Price</th>
      <th>Status</th>
      <th>Sold by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.condition %></td>
        <td><%= car.location_address %></td>
        <td><%= car.location_city %></td>
        <td><%= car.location_state %></td>
        <td><%= car.location_zip %></td>
        <td><%= car.price %></td>
        <td><%= car.status %></td>
        <td><%= car.sold_by %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @car.condition %>
</p>

<p>
  <strong>Location address:</strong>
  <%= @car.location_address %>
</p>

<p>
  <strong>Location city:</strong>
  <%= @car.location_city %>
</p>

<p>
  <strong>Location state:</strong>
  <%= @car.location_state %>
</p>

<p>
  <strong>Location zip:</strong>
  <%= @car.location_zip %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car.status %>
</p>

<p>
  <strong>Sold by:</strong>
  <%= @car.sold_by %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/dealerships/_form.html.erb
<%= form_for(@dealership) do |f| %>
  <% if @dealership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

      <ul>
      <% @dealership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dealerships/edit.html.erb
<h1>Editing Dealership</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealership %> |
<%= link_to 'Back', dealerships_path %>

app/views/dealerships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dealerships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealerships.each do |dealership| %>
      <tr>
        <td><%= dealership.name %></td>
        <td><%= dealership.address %></td>
        <td><%= dealership.city %></td>
        <td><%= dealership.state %></td>
        <td><%= dealership.zip %></td>
        <td><%= dealership.owner %></td>
        <td><%= link_to 'Show', dealership %></td>
        <td><%= link_to 'Edit', edit_dealership_path(dealership) %></td>
        <td><%= link_to 'Destroy', dealership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealership', new_dealership_path %>

app/views/dealerships/new.html.erb
<h1>New Dealership</h1>

<%= render 'form' %>

<%= link_to 'Back', dealerships_path %>

app/views/dealerships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dealership.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @dealership.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @dealership.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @dealership.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @dealership.zip %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @dealership.owner %>
</p>

<%= link_to 'Edit', edit_dealership_path(@dealership) %> |
<%= link_to 'Back', dealerships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarDealerships</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prospects/_form.html.erb
<%= form_for(@prospect) do |f| %>
  <% if @prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% @prospect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :mobile_phone_number %><br>
    <%= f.text_field :mobile_phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editing Prospect</h1>

<%= render 'form' %>

<%= link_to 'Show', @prospect %> |
<%= link_to 'Back', prospects_path %>

app/views/prospects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prospects</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Mobile phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= prospect.first_name %></td>
        <td><%= prospect.last_name %></td>
        <td><%= prospect.email_address %></td>
        <td><%= prospect.address %></td>
        <td><%= prospect.city %></td>
        <td><%= prospect.state %></td>
        <td><%= prospect.zip %></td>
        <td><%= prospect.mobile_phone_number %></td>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
        <td><%= link_to 'Destroy', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path %>

app/views/prospects/new.html.erb
<h1>New Prospect</h1>

<%= render 'form' %>

<%= link_to 'Back', prospects_path %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @prospect.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @prospect.last_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @prospect.email_address %>
</p>

<p>
  <strong>Address:</strong>
  <%= @prospect.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @prospect.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @prospect.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @prospect.zip %>
</p>

<p>
  <strong>Mobile phone number:</strong>
  <%= @prospect.mobile_phone_number %>
</p>

<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>

app/views/salesmen/_form.html.erb
<%= form_for(@salesman) do |f| %>
  <% if @salesman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salesman.errors.count, "error") %> prohibited this salesman from being saved:</h2>

      <ul>
      <% @salesman.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salesmen/edit.html.erb
<h1>Editing Salesman</h1>

<%= render 'form' %>

<%= link_to 'Show', @salesman %> |
<%= link_to 'Back', salesmen_path %>

app/views/salesmen/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Salesmen</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salesmen.each do |salesman| %>
      <tr>
        <td><%= salesman.first_name %></td>
        <td><%= salesman.last_name %></td>
        <td><%= salesman.email_address %></td>
        <td><%= link_to 'Show', salesman %></td>
        <td><%= link_to 'Edit', edit_salesman_path(salesman) %></td>
        <td><%= link_to 'Destroy', salesman, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salesman', new_salesman_path %>

app/views/salesmen/new.html.erb
<h1>New Salesman</h1>

<%= render 'form' %>

<%= link_to 'Back', salesmen_path %>

app/views/salesmen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @salesman.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @salesman.last_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @salesman.email_address %>
</p>

<%= link_to 'Edit', edit_salesman_path(@salesman) %> |
<%= link_to 'Back', salesmen_path %>